name: Build and Run C++ Code

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change it to 'windows-latest' or 'macos-latest' if needed

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout
